# Generated by Django 4.1.3 on 2022-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID_STD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=11)),
            ],
        ),
    ]
