# Generated by Django 4.1.3 on 2022-12-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
