# Generated by Django 4.1.3 on 2022-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_admin', '0002_addroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addroom',
            name='status',
            field=models.CharField(choices=[('OPEN', 'พร้อมให้จอง'), ('NOTOPEN', 'ปิดชั่วคราว')], default='OPEN', max_length=100),
        ),
    ]
