# Generated by Django 4.1.3 on 2022-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp_admin", "0003_alter_addroom_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addroom",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "OPEN"), ("NOTOPEN", "CLOSE")],
                default="OPEN",
                max_length=100,
            ),
        ),
    ]
